# site settings
title: "Indiska Boxen"
meta_title: "Färdiglagad nyttig näringsrik fryst indisk mat med råvaror från Sverige levererar direkt till din dörr"
meta_desc: "njut av fantastiskt god indisk mat när som helst"
meta_keywords: "matlåda indiskmat lunchbox indianfood"
subtitle: ""
email: info@indiskaboxen.se
landing-title: "Färdiglagad nyttig näringsrik fryst indisk mat med råvaror från Sverige levererar direkt till din dörr"
description: "njut av fantastiskt god indisk mat när som helst"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.indiskaboxen.se" # the base hostname & protocol for your site
author:
name: Indiska Boxen Handelsbolag
street_address:
city: Stockholm
Län: 
zip_code:
country: 
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/indiskaboxen/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/indiskaboxen/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
