# site settings
total: 590
users: 6
title: "Indiska Boxen"
meta_title: "Färdiglagad näringsrik klimatsmart fryst indisk mat när som helst"
meta_desc: "Indiska Boxen erbjuder portionspackat frysta matlådor som har låg klimatpåverkan och förlängd livslängd. Vi förhindrar matsvinn genom att frysa in nylagad mat. Vi tror på ett proaktivt tillvägagångssätt som fokuserar på att eliminera matsvinn innan de har en chans att dyka upp."
meta_keywords: "matlåda indiskmat lunchbox indianfood"
subtitle: ""
email: info@indiskaboxen.se
landing-title: "Färdiglagad näringsrik klimatsmart fryst indisk mat när som helst"
description: "Indiska Boxen erbjuder portionspackat frysta matlådor som har låg klimatpåverkan och förlängd livslängd. Vi förhindrar matsvinn genom att frysa in nylagad mat. Vi tror på ett proaktivt tillvägagångssätt som fokuserar på att eliminera matsvinn innan de har en chans att dyka upp."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.indiskaboxen.se" # the base hostname & protocol for your site
author:
name: Indiska Boxen AB
street_address:
city: Stockholm
Län: 
zip_code:
country: 
phone:
lang: se
languages: ["en", "se"]
# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/indiskaboxen/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/indiskaboxen/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
