# site settings
title: "Indiska Boxen"
subtitle: ""
email: info@indiskaboxen.se
description: "f채rdiglagad nyttig n채ringsriktig fryst indisk mat n채r som helst"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: indiskaboxen Handelsbolag
city: 
L채n: 
zip_code: 
country: 
phone: 072-539 83 64

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/indiskaboxen/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/indiskaboxen/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
